---
name: Lexipath
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: npm install

    - name: Deploy
      run: |
        git config --global user.name 'Maksym Bondar'
        git config --global user.email 'maksimbondar225@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
        npm run deploy